apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{NAME}}
  namespace: dynamic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{NAME}}
  template:
    metadata:
      labels:
        app: {{NAME}}
    spec:
      containers:
      - name: app
        image: {{IMAGE}}
        ports:
        - containerPort: 8000
        env:
        - name: SERVICE_NAME
          value: "{{SERVICE_NAME}}"
        - name: ENV
          value: "{{ENV}}"
        - name: CUSTOM_VALUE
          value: "{{CUSTOM_VALUE}}"
