name: Test AWS OIDC

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Verify AWS Identity
      run: aws sts get-caller-identity
